Controllers/CatagoryController.cs
using e_commerce.Models;
using e_commerce.Servies;
using e_commerce.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace e_commerce.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize(Roles = ("Admin"))]
    public class CatagoryController : Controller
    {
        private readonly ICatagoryServies catagoryServies;

        public CatagoryController(ICatagoryServies _catagoryServies)
        {
            catagoryServies = _catagoryServies;
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Catagory newCatagory)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    //Catagory catagory = new Catagory
                    //{
                    //    Name = newCatagory.Name,
                    //    Description = newCatagory.Description
                    //};
                    await catagoryServies.Create(newCatagory);
                    return RedirectToAction("List");

                }
                else
                {
                    return BadRequest("Please Check And Try Again");
                }
              
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Create");
            }
        }
        public async Task<IActionResult> List()
        {
            return View(await catagoryServies.getAll());
        }
        public async Task<IActionResult> Delete(int id)
        {
            Catagory catagory = await catagoryServies.getById(id);
            if (catagory == null)
                return BadRequest("Catagory Not Found");
      
            return View(catagory);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Catagory catagory)
        {
            try
            {
                await catagoryServies.Delete(catagory);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Delete");
            }
        }
        public async Task<ActionResult> Edit(int id)
        {

            Catagory catagory = await catagoryServies.getById(id);
            if (catagory == null)
                return BadRequest("This Catagory Is Not Found");
            return View(catagory);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit( [FromForm]Catagory catagory)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    await catagoryServies.Update(catagory);
                    return RedirectToAction("List");
                }
                else
                {
                    return BadRequest("Plese Try Again");
                }
              
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Edit");
            }
            }
    }
}

Controllers/OfferController.cs
using e_commerce.Models;
using e_commerce.Servies;
using e_commerce.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace e_commerce.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize(Roles = ("Admin"))]
    public class OfferController : Controller

    {
        private readonly IOfferServies offerServies;

        public OfferController(IOfferServies _offerServies)
        {
            offerServies = _offerServies;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Offer newoffer) 
        {
            try
            {
                if (ModelState.IsValid == true) 
                {
                    await offerServies.Create(newoffer);
                    return RedirectToAction("List");
                }
                else
                    return BadRequest("Please Check And Try Again");
                
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception",ex.InnerException.Message);
                return RedirectToAction("Create");
            }
        
        }
      
        public async Task<IActionResult> List()
        {
            return View(await offerServies.getAll());
        }
        public async Task<IActionResult> Delete(int id)
        {
            Offer offer = await offerServies.getById(id);
            if (offer == null)
                return BadRequest("Stock Not Found");
            return View(offer);

        }
        [HttpPost]

        public async Task<IActionResult> Delete(Offer offer)
        {
    
            try
            {
                await offerServies.Delete(offer);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Delete");
            }
        }
        public async Task <IActionResult> Edit(int id)
        {
            Offer offer = await offerServies.getById(id);
            if (offer == null)
                return BadRequest("This Catagory Is Not Found");
            return View(offer);

        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute]int id,[FromForm] Offer offer)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    await offerServies.Update(offer);
                    return RedirectToAction("List");

                }
                else
                     return BadRequest("Plese Try Again");
                
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Edit");
            }

        }

    }
}

Controllers/ProductController.cs
using e_commerce.Models;
using e_commerce.Servies;
using e_commerce.ViewModel;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace e_commerce.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductServies productServies;
        private readonly IOfferServies offerServies;
        private readonly ICatagoryServies catagoryServies;

        public ProductController(IProductServies _productServies,IOfferServies _offerServies,ICatagoryServies _catagoryServies)
        {
            productServies = _productServies;
            offerServies = _offerServies;
            catagoryServies = _catagoryServies;
           
        }
        [Authorize(Roles = ("Admin"))]

        public async Task <IActionResult> Create()
        {
            IEnumerable <Catagory> catagories= await catagoryServies.getAll();
            IEnumerable <Offer> offers= await offerServies.getAll();
            ViewData["cat"] = catagories;
            ViewData["offer"] = offers;
      
            //  ViewData["stock"] = stocks;
            return View();
        }
       [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = ("Admin"))]
       public async Task<IActionResult>Create([FromForm]EditProductViewModel newproduct)
       {

            try
            {
                Product product = new Product();

                using (var DataStream = new MemoryStream())
                {
                    await newproduct.Photo.CopyToAsync(DataStream);
                    byte[] data = DataStream.ToArray();
                    product.Name = newproduct.Name;
                    product.Description = newproduct.Description;
                    product.Photo = data;
                    product.Price = newproduct.Price;
                    product.Create_at = DateTime.Now;
                    if (newproduct.CatagortId == 0)
                        product.CatagoryId = 1;
                    else product.CatagoryId = newproduct.CatagortId;
                    if (newproduct.OfferId == 0)
                        product.OfferId = 1;
                    else
                    product.OfferId = newproduct.OfferId;
                };
                  await productServies.Create(product);
                  return RedirectToAction("List");

              
               
                    
                // return Content("Create is Done");
             
            }
            catch (Exception ex) {
                ModelState.AddModelError("Exception","Plese Enter Valid Input ");
                return BadRequest("Be Carful And Try Again");

            }
        }
        public async Task<IActionResult> List()
        {
            return View(await productServies.getAll());
        }
        public async Task<IActionResult> Search(int id)
        {
            var product = await productServies.getById(id);
            if (product is null)
                return BadRequest("Product not found");

            return View(product);
        }
        public async Task<ActionResult> Details(int id)
        {
            Product product =await productServies.getById(id);
             ViewData["catagory"] = await productServies.getCatagory(product.CatagoryId);
             ViewData["offer"] = await productServies.getOffer(product.OfferId);

            if (product == null)
                return BadRequest("This Product Is Not Found ");
            return View(product);
        }
        [Authorize(Roles = ("Admin"))]

        public async Task<ActionResult> Edit(int id)
        {
            Product product=await productServies.getById(id);
            IEnumerable<Catagory> catagories = await catagoryServies.getAll();
            IEnumerable<Offer> offers = await offerServies.getAll();
            ViewData["cat"] = catagories;
            ViewData["offer"] = offers;
            if (product == null)
                return BadRequest("This Product Is Not Found ");
            return View(product);
        }
        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = ("Admin"))]

        public async Task<ActionResult> Edit(int id,[FromForm]Product product,IFormFile photo)
        {
            try
            {

                Product oldproduct = await productServies.getById(id);

                if (photo is not null)
                {
                    using (var DataStream = new MemoryStream())
                    {
                        await photo.CopyToAsync(DataStream);
                        byte[] data = DataStream.ToArray();
                      
                       await productServies.Update(id ,product, data);
                        
                    }
                }
                else if (photo is null)
                {
                    await productServies.Update(id, product);

                }
                else
                    return BadRequest("This Product Is Not Found ");
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Edit");
            }
     }
        public async Task<IActionResult> Delete(int id)
        {
            Product product = await productServies.getById(id);
            ViewData["catagory"] = await productServies.getCatagory(product.CatagoryId);
            ViewData["offer"] = await productServies.getOffer(product.OfferId);
            if (product == null)
                return BadRequest("Product Not Found");
            return View(product);

        }
        [HttpPost]

        public async Task<IActionResult> Delete(Product product)
        {

            try
            {
                await productServies.Delete(product);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Delete");
            }
        }

    }
}

Controllers/RoleController.cs
using e_commerce.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Win32;
using System.Data;
using System.Security.Principal;
using System.Text;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace e_commerce.Controllers
{
    [Authorize(Roles = ("Admin"))]

    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public RoleController(RoleManager<IdentityRole> _roleManager,UserManager<IdentityUser> _userManager,SignInManager<IdentityUser>_signInManager)
        {
            roleManager = _roleManager;
            userManager = _userManager;
            signInManager = _signInManager;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] RoleViewModel newRole)
        {
            if (ModelState.IsValid == true)
            {
                IdentityRole role = new IdentityRole { Name = newRole.RoleName };
                IdentityResult result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return View("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);

                    }
                    return BadRequest("Somting Is wrong");


                }
            }
            else 
            {
                return BadRequest("Somting Is wrong");
            }
        }
        public IActionResult addAdminToRole()
        {
            return View();
        }
        [HttpPost,ValidateAntiForgeryToken]
        public async Task <IActionResult> addAdminToRole([FromForm]RegsisterAdminViewModel newAdim)
        {
            if (ModelState.IsValid == true)
            {
                IdentityUser user = new IdentityUser {UserName=newAdim.Name,Email=newAdim.Email };
              IdentityResult result= await userManager.CreateAsync (user,newAdim.Password);
                if (result.Succeeded)
                {
                    //add Admin Role
                    await userManager.AddToRoleAsync(user, "Admin");
                    //create cookie
                    await signInManager.SignInAsync(user, false);
                    //congirm email
                    var code = await userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
                     await userManager.ConfirmEmailAsync(user, code);

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {

                        ModelState.AddModelError("", error.Description);
                    }
                }
                }
                return View(newAdim);
            }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable< Product>
@{
    ViewData["Title"] = "Home Page";
}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Infinity Shop</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome You In Our Shop</p>
        </div>
    </div>
</header>
<section id="collection" class="py-5">
    <div class="collection-list mt-4 row gx-0 gy-3">
     @{
            foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-4 col-xl-3 p-2 best">
                    <div class="collection-img position-relative overflow-hidden">
                        <a class="btn btn-outline-dark mt-auto" asp-action="Details" asp-controller="Product" asp-route-id="@item.Id">
                            <img  src="data:image;base64,@System.Convert.ToBase64String(item.Photo)" alt="Photo" class="w-100" height="250px" width="250px" />
                            <span class="position-absolute bg-primary text-white d-flex align-items-center justify-content-center">sale</span>
                        </a>
                    </div>


                    <div class="text-center">
                        <div class="rating mt-3">
                            <span class="text-primary"><i class="fas fa-star"></i></span>
                            <span class="text-primary"><i class="fas fa-star"></i></span>
                            <span class="text-primary"><i class="fas fa-star"></i></span>
                            <span class="text-primary"><i class="fas fa-star"></i></span>
                            <span class="text-primary"><i class="fas fa-star"></i></span>
                        </div>
                        <p class="text-capitalize my-1">@item.Name</p>
                        <span class="fw-bold">$@item.Price</span>
                    </div>
                </div>


            }
        }


    </div>
    </div>
    </div>
</section>

Views/Home/settings.cshtml
<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Category Settings</a>
            <a class="list-group-item list-group-item-action" id="list-Create-list" data-toggle="list" role="tab" aria-controls="Create" asp-controller="Catagory" asp-action="Create" asp-area="">Add Category</a>
            <a class="list-group-item list-group-item-action" id="list-ALl-list" data-toggle="list" role="tab" aria-controls="All" asp-controller="Catagory" asp-action="List" asp-area="">Delete or Edit Category</a>

    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">...</div>
      <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">...</div>
      <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
      <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
    </div>
  </div>
</div>


<hr>


<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Offer Settings</a>
            <a class="list-group-item list-group-item-action" id="list-Create-list" data-toggle="list"  role="tab" aria-controls="Create" asp-controller="Offer" asp-action="Create"  asp-area="" >Create Offer</a>
      <a class="list-group-item list-group-item-action" id="list-ALl-list" data-toggle="list"  role="tab" aria-controls="List" asp-controller="Offer" asp-action="List"  asp-area="" >Delete or Edit Offer</a>

    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">...</div>
      <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">...</div>
      <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
      <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
    </div>
  </div>
</div>


<hr>



<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Product Settings</a>
            <a class="list-group-item list-group-item-action" id="list-Create-list" data-toggle="list"  role="tab" aria-controls="Create" asp-controller="Product" asp-action="Create"  asp-area="" >Create Product</a>
            <a class="list-group-item list-group-item-action" id="list-ALl-list" data-toggle="list" role="tab" aria-controls="List" asp-controller="Product" asp-action="List" asp-area="">Delete or Edit Product</a>

    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">...</div>
      <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">...</div>
      <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
      <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
    </div>
  </div>
</div>

<hr>
<div class="row">
    <div class="col-4">
        <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Admin Settings</a>
            <a class="list-group-item list-group-item-action" id="list-Create-list" data-toggle="list" role="tab" aria-controls="Create" asp-controller="Role" asp-action="addAdminToRole" asp-area="">Add new Admin</a>
            <a class="list-group-item list-group-item-action" id="list-Create-list" data-toggle="list" role="tab" aria-controls="Create" asp-controller="Role" asp-action="Create" asp-area="">Add new Role</a>
        </div>
    </div>
    <div class="col-8">
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">...</div>
            <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">...</div>
            <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
            <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
        </div>
    </div>
</div>