Models/Cart.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations.Schema;

namespace e_commerce.Models
{
    public class Cart
    {
        public int Id { get; set; }
        [ForeignKey("product")]
        public int ProductId { get; set; }
        public Product? product { get; set; }
        public int Quantity { get; set; }
        public string? UserID { get; set; }
        public IdentityUser? UserName { get; set; }
    }
}

Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using e_commerce.Configrution;
using e_commerce.Models;
using e_commerce.Servies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace e_commerce.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartServies cartServies;
        private readonly UserManager<IdentityUser> userManager;

        public CartController(ICartServies _cartServies, UserManager<IdentityUser> _userManager)
        {
            cartServies = _cartServies;
            userManager = _userManager;
        }


        public IActionResult Index()
        {
            var userId = userManager.GetUserId(User);

            return View(cartServies.GetAll(userId));
        }
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                Cart cart = await cartServies.GetCartById(id);
                if (cart is null)
                    return NotFound("Please Try Again");
                else
                {
                    await cartServies.Delete(cart);
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", "Somting Is Wrong");
                return RedirectToAction("Index");

            }

        }
        public async Task<IActionResult> Edit(int CardId, int Quantity)
        {
            Cart cart = await cartServies.GetCartById(CardId);
            cart.Quantity = +Quantity;
            await cartServies.Update(cart);
            return RedirectToAction("Index");
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> addToCard(int productId, int Quantity)
        {
            try
            {
                var UserId = userManager.GetUserId(User);
                Cart existCart = await cartServies.GetUserCart(productId, UserId);
                if (existCart is null)
                {
                    Cart cart = new Cart
                    {
                        ProductId = productId,
                        Quantity = Quantity,
                        UserID = UserId
                    };
                    await cartServies.Create(cart);
                }
                else
                {
                    existCart.Quantity += Quantity;
                    await cartServies.Update(existCart);
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", "Sometjing Is Wrong");
                return RedirectToAction("Index");
            }
        }
     
    }
}

Controllers/OrderController.cs
using e_commerce.Models;
using e_commerce.Servies;
using e_commerce.ViewModel;
using First_MVC.Servies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace e_commerce.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderServies orderServies;
        private readonly ICartServies cartServies;
        private readonly IProductServies productServies;
        private readonly UserManager<IdentityUser> userManager;

        public OrderController(IOrderServies _orderServies,ICartServies _cartServies,IProductServies _productServies,UserManager<IdentityUser> _userManager)
        {
            orderServies = _orderServies;
            cartServies = _cartServies;
            productServies = _productServies;
            userManager = _userManager;
        }
        public IActionResult Create(double total)
        {
            
            return View();
        }
        [HttpPost,ValidateAntiForgeryToken]
       public async Task<IActionResult> Create([FromForm]OrderViewModel newOrder)
       {
            try
            {
                var userId = userManager.GetUserId(User);
                IEnumerable<Cart> cart = cartServies.GetAll(userId);
                OrderDeteils orderDeteils = new OrderDeteils
                {
                    Name = newOrder.Name,
                    Adress = newOrder.Address,
                    Phone = newOrder.Phone,
                    UserID = userId,
                    CreatedDate = DateTime.Now,
                    Total=newOrder.TotalAmount
                };
                int id = await orderServies.CreateOrderDeteils(orderDeteils);

                Order order = new Order();
                order.OrderDetailsId = id;

                foreach (var item in cart)
                {
                    order.ProuductId += item.ProductId;
                    order.Quantity += item.Quantity;
                    order.Price += orderDeteils.Total*item.Quantity;
                };
                    await orderServies.CreateOrder(order);
                
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", "Something Was Wrong");
                return View();
            }
        }


       public async Task <IActionResult> MyOrder()
        {
            var userId =userManager.GetUserId(User);
            return View(await orderServies.MyOrders(userId));

        }

       public async Task <IActionResult> Delete(int id)
        {
            try
            {
                OrderDeteils order = await orderServies.getById(id);
                if (order == null)
                    return NotFound("Sorry I Can Not Found ");
                else
                {
                    await orderServies.DeleteOrder(order);
                    return RedirectToAction("MyOrder");
                }
            }
            catch (Exception ex){
                ModelState.AddModelError("Exception", "Something Was Wrong");
                return RedirectToAction("MyOrder");
            }
        }



    }
}

Controllers/ProductController.cs
using e_commerce.Models;
using e_commerce.Servies;
using e_commerce.ViewModel;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace e_commerce.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductServies productServies;
        private readonly IOfferServies offerServies;
        private readonly ICatagoryServies catagoryServies;

        public ProductController(IProductServies _productServies,IOfferServies _offerServies,ICatagoryServies _catagoryServies)
        {
            productServies = _productServies;
            offerServies = _offerServies;
            catagoryServies = _catagoryServies;
           
        }
        [Authorize(Roles = ("Admin"))]

        public async Task <IActionResult> Create()
        {
            IEnumerable <Catagory> catagories= await catagoryServies.getAll();
            IEnumerable <Offer> offers= await offerServies.getAll();
            ViewData["cat"] = catagories;
            ViewData["offer"] = offers;
      
            //  ViewData["stock"] = stocks;
            return View();
        }
       [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = ("Admin"))]
       public async Task<IActionResult>Create([FromForm]EditProductViewModel newproduct)
       {

            try
            {
                Product product = new Product();

                using (var DataStream = new MemoryStream())
                {
                    await newproduct.Photo.CopyToAsync(DataStream);
                    byte[] data = DataStream.ToArray();
                    product.Name = newproduct.Name;
                    product.Description = newproduct.Description;
                    product.Photo = data;
                    product.Price = newproduct.Price;
                    product.Create_at = DateTime.Now;
                    if (newproduct.CatagortId == 0)
                        product.CatagoryId = 1;
                    else product.CatagoryId = newproduct.CatagortId;
                    if (newproduct.OfferId == 0)
                        product.OfferId = 1;
                    else
                    product.OfferId = newproduct.OfferId;
                };
                  await productServies.Create(product);
                  return RedirectToAction("List");

              
               
                    
                // return Content("Create is Done");
             
            }
            catch (Exception ex) {
                ModelState.AddModelError("Exception","Plese Enter Valid Input ");
                return BadRequest("Be Carful And Try Again");

            }
        }
        public async Task<IActionResult> List()
        {
            return View(await productServies.getAll());
        }
        public async Task<IActionResult> Search(int id)
        {
            var product = await productServies.getById(id);
            if (product is null)
                return BadRequest("Product not found");

            return View(product);
        }
        public async Task<ActionResult> Details(int id)
        {
            Product product =await productServies.getById(id);
             ViewData["catagory"] = await productServies.getCatagory(product.CatagoryId);
             ViewData["offer"] = await productServies.getOffer(product.OfferId);

            if (product == null)
                return BadRequest("This Product Is Not Found ");
            return View(product);
        }
        [Authorize(Roles = ("Admin"))]

        public async Task<ActionResult> Edit(int id)
        {
            Product product=await productServies.getById(id);
            IEnumerable<Catagory> catagories = await catagoryServies.getAll();
            IEnumerable<Offer> offers = await offerServies.getAll();
            ViewData["cat"] = catagories;
            ViewData["offer"] = offers;
            if (product == null)
                return BadRequest("This Product Is Not Found ");
            return View(product);
        }
        [HttpPost, ValidateAntiForgeryToken, Authorize(Roles = ("Admin"))]

        public async Task<ActionResult> Edit(int id,[FromForm]Product product,IFormFile photo)
        {
            try
            {

                Product oldproduct = await productServies.getById(id);

                if (photo is not null)
                {
                    using (var DataStream = new MemoryStream())
                    {
                        await photo.CopyToAsync(DataStream);
                        byte[] data = DataStream.ToArray();
                      
                       await productServies.Update(id ,product, data);
                        
                    }
                }
                else if (photo is null)
                {
                    await productServies.Update(id, product);

                }
                else
                    return BadRequest("This Product Is Not Found ");
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Edit");
            }
     }
        public async Task<IActionResult> Delete(int id)
        {
            Product product = await productServies.getById(id);
            ViewData["catagory"] = await productServies.getCatagory(product.CatagoryId);
            ViewData["offer"] = await productServies.getOffer(product.OfferId);
            if (product == null)
                return BadRequest("Product Not Found");
            return View(product);

        }
        [HttpPost]

        public async Task<IActionResult> Delete(Product product)
        {

            try
            {
                await productServies.Delete(product);
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Exception", ex.InnerException.Message);
                return RedirectToAction("Delete");
            }
        }

    }
}

Views/Cart/Index.cshtml
@model IEnumerable<Cart>
@inject IProductServies productservice;
@inject IOfferServies offerservice;

<div class="container-fluid">
        <div class="row">
  <aside class="col-lg-9">
 <section class="h-100 h-custom" style="background-color: #eee;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card">
          <div class="card-body p-4">

            <div class="row">

              <div class="col-lg-7">
                <hr>

                <div class="d-flex justify-content-between align-items-center mb-4">
                  <div>
                    <p class="mb-1">Shopping cart</p>
                    <p class="mb-0">You have @Model.Count() items in your cart</p>
                  </div>
                  <div>
                    <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!"
                        class="text-body">price<i class="fas fa-angle-down mt-1"></i></a></p>
                  </div>
                </div>
@{
    double Total = 0 ;


    foreach (var item in Model)
    {
   var product = await productservice.getById(item.ProductId);
   var offer = await offerservice.getById(product.OfferId);

       var price = (product.Price * item.Quantity);
          Total +=(double)price;
       <div class="card mb-3">
       <div class="card-body" >
               <div class="d-flex justify-content-between">
                   <div class="d-flex flex-row align-items-center">
                       <div>
                  <a asp-area="" asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">
                               <img src="data:image;base64,@System.Convert.ToBase64String(@product.Photo)"
                                    class="img-fluid rounded-3" alt="Shopping item" style="width: 150px;" />
                           </a>

                       </div>
                       <div class="ms-3">
                           <h5>@product.Name</h5>
                           <p class="small mb-0">Onyx Black</p>
                       </div>
                   </div>
                   <div class="d-flex flex-row align-items-center">
                       <div style="width: 80px;">
                           <label>Quantity</label>
                           <h5 class="fw-normal mb-0">@item.Quantity</h5>
                       </div>

                       <div style="width: 80px;">
                           <label>Price</label>
                           <h5 class="mb-0">$@price</h5>
                       </div>


                       <div style="width: 120px;">
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Cart" asp-route-id="@item.Id">Delete</a>
                       </div>

                       <a href="#!" style="color: #cecece;"><i class="fas fa-trash-alt"></i></a>
                   </div>
               </div>
           </div>
          </div>
                        }                             }
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </div>
 </section>
  </aside>
        <aside class="col-lg-3">
            <div class="card">
                <div class="card-body">
                    <dl class="dlist-align">
                        <dt>Total price:</dt>
                        <dd class="text-right ml-3">$@Total</dd>
                    </dl>
                    <dl class="dlist-align">
                        <dt>Discount:</dt>
                        <dd class="text-right text-danger ml-3">- $10.00</dd> 
                    </dl>
                    <dl class="dlist-align">
                        <dt>Total:</dt>
                        <dd class="text-right text-dark b ml-3"><strong>$@Total</strong></dd>
                    </dl>
                    <hr> <a asp-controller="Order" asp-action="Create"  class="btn btn-out btn-primary btn-square btn-main" data-abc="true"> Make Purchase </a>
                    <a class="btn btn-out btn-success btn-square btn-main mt-2" data-abc="true" asp-controller="Home" asp-action="Index">Continue Shopping</a>
                </div>
            </div>
        </aside>
    </div>
</div>